### ISSUE TITLE
User-defined color schemes

### ISSUE THREAD

**Issue by liquidev** [liquidev/netcanv#112]
It would be nice to have color schemes that are fully user-definable.

**Comment by liquidev** [comment]
A few things to note:
- The format should be TOML.
- It should be possible to define variables inside the color scheme, so that sharing colors is easy. For instance:
```toml
[variables]
gray-00 = "#000000"

[colors]
panel = gray-00
```
